### ISSUE TITLE
when i meet Error while "Running the code"

### ISSUE THREAD

**Issue by wahihijames** [Jaeyoung-Lim/mavros_controllers#218]
I typing and start --> $ roslaunch geometric_controller sitl_trajectory_track_circle.launch

but I meet this error.
To solve the problem, what should I do?

(설치 다 끝내고, 실행 시키니깐, 아래와 같이 에러가 나와요) 
어디가 문제여서 발생한 걸까요?

```
================================================================================REQUIRED process [sitl-5] has died!

process has died [pid -1, exit code 255, cmd /home/wahihi/src/Firmware/build/px4_sitl_default/bin/px4 /home/wahihi/src/Firmware/build/px4_sitl_default/etc -s etc/init.d-posix/rcS __name:=sitl __log:=/home/wahihi/.ros/log/1271b0e8-e85c-11ec-9955-13fe95e71a1f/sitl-5.log].

log file: /home/wahihi/.ros/log/1271b0e8-e85c-11ec-9955-13fe95e71a1f/sitl-5*.log

Initiating shutdown!

================================================================================[ INFO] [1654827947.869619412, 3670.196000000]: Plugin gps_input initialized

[ INFO] [1654827947.871909011, 3670.200000000]: Plugin gps_rtk loaded


++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```
[ This is my log ]
아래는, 제가 실행 했을때, 터미널에서 나온 메시지 입니다.
```
wahihi@wahihi-VirtualBox:~/catkin_ws$ roslaunch geometric_controller sitl_trajectory_track_circle.launch

... logging to /home/wahihi/.ros/log/1271b0e8-e85c-11ec-9955-13fe95e71a1f/roslaunch-wahihi-VirtualBox-13686.log

Checking log directory for disk usage. This may take a while.

Press Ctrl-C to interrupt

Done checking log file disk usage. Usage is <1GB.

​

started roslaunch server http://wahihi-virtualbox:36183/

​

SUMMARY

========

​

CLEAR PARAMETERS

 * /mavros/

​

PARAMETERS

 * /gazebo/enable_ros_network: True

 * /geometric_controller/Kp_x: 10.0

 * /geometric_controller/Kp_y: 10.0

 * /geometric_controller/Kp_z: 20.0

 * /geometric_controller/Kv_x: 5.0

 * /geometric_controller/Kv_y: 5.0

 * /geometric_controller/Kv_z: 10.0

 * /geometric_controller/attctrl_constant: 0.3

 * /geometric_controller/ctrl_mode: 2

 * /geometric_controller/enable_gazebo_state: True

 * /geometric_controller/enable_sim: True

 * /geometric_controller/mav_name: iris

 * /geometric_controller/max_acc: 10.0

 * /geometric_controller/normalizedthrust_constant: 0.06

 * /geometric_controller/normalizedthrust_offset: 0.1

 * /mavros/camera/frame_id: base_link

 * /mavros/cmd/use_comp_id_system_control: False

 * /mavros/conn/heartbeat_rate: 1.0

 * /mavros/conn/system_time_rate: 1.0

 * /mavros/conn/timeout: 10.0

 * /mavros/conn/timesync_rate: 10.0

 * /mavros/distance_sensor/hrlv_ez4_pub/field_of_view: 0.0

 * /mavros/distance_sensor/hrlv_ez4_pub/frame_id: hrlv_ez4_sonar

 * /mavros/distance_sensor/hrlv_ez4_pub/id: 0

 * /mavros/distance_sensor/hrlv_ez4_pub/orientation: PITCH_270

 * /mavros/distance_sensor/hrlv_ez4_pub/send_tf: True

 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/x: 0.0

 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/y: 0.0

 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/z: -0.1

 * /mavros/distance_sensor/laser_1_sub/id: 3

 * /mavros/distance_sensor/laser_1_sub/orientation: PITCH_270

 * /mavros/distance_sensor/laser_1_sub/subscriber: True

 * /mavros/distance_sensor/lidarlite_pub/field_of_view: 0.0

 * /mavros/distance_sensor/lidarlite_pub/frame_id: lidarlite_laser

 * /mavros/distance_sensor/lidarlite_pub/id: 1

 * /mavros/distance_sensor/lidarlite_pub/orientation: PITCH_270

 * /mavros/distance_sensor/lidarlite_pub/send_tf: True

 * /mavros/distance_sensor/lidarlite_pub/sensor_position/x: 0.0

 * /mavros/distance_sensor/lidarlite_pub/sensor_position/y: 0.0

 * /mavros/distance_sensor/lidarlite_pub/sensor_position/z: -0.1

 * /mavros/distance_sensor/sonar_1_sub/horizontal_fov_ratio: 1.0

 * /mavros/distance_sensor/sonar_1_sub/id: 2

 * /mavros/distance_sensor/sonar_1_sub/orientation: PITCH_270

 * /mavros/distance_sensor/sonar_1_sub/subscriber: True

 * /mavros/distance_sensor/sonar_1_sub/vertical_fov_ratio: 1.0

 * /mavros/fake_gps/eph: 2.0

 * /mavros/fake_gps/epv: 2.0

 * /mavros/fake_gps/fix_type: 3

 * /mavros/fake_gps/geo_origin/alt: 408.0

 * /mavros/fake_gps/geo_origin/lat: 47.3667

 * /mavros/fake_gps/geo_origin/lon: 8.55

 * /mavros/fake_gps/gps_rate: 5.0

 * /mavros/fake_gps/mocap_transform: True

 * /mavros/fake_gps/satellites_visible: 5

 * /mavros/fake_gps/tf/child_frame_id: fix

 * /mavros/fake_gps/tf/frame_id: map

 * /mavros/fake_gps/tf/listen: False

 * /mavros/fake_gps/tf/rate_limit: 10.0

 * /mavros/fake_gps/tf/send: False

 * /mavros/fake_gps/use_mocap: True

 * /mavros/fake_gps/use_vision: False

 * /mavros/fcu_protocol: v2.0

 * /mavros/fcu_url: udp://:14540@127....

 * /mavros/gcs_url: 

 * /mavros/global_position/child_frame_id: base_link

 * /mavros/global_position/frame_id: map

 * /mavros/global_position/gps_uere: 1.0

 * /mavros/global_position/rot_covariance: 99999.0

 * /mavros/global_position/tf/child_frame_id: base_link

 * /mavros/global_position/tf/frame_id: map

 * /mavros/global_position/tf/global_frame_id: earth

 * /mavros/global_position/tf/send: False

 * /mavros/global_position/use_relative_alt: True

 * /mavros/image/frame_id: px4flow

 * /mavros/imu/angular_velocity_stdev: 0.0003490659 // 0...

 * /mavros/imu/frame_id: base_link

 * /mavros/imu/linear_acceleration_stdev: 0.0003

 * /mavros/imu/magnetic_stdev: 0.0

 * /mavros/imu/orientation_stdev: 1.0

 * /mavros/landing_target/camera/fov_x: 2.0071286398

 * /mavros/landing_target/camera/fov_y: 2.0071286398

 * /mavros/landing_target/image/height: 480

 * /mavros/landing_target/image/width: 640

 * /mavros/landing_target/land_target_type: VISION_FIDUCIAL

 * /mavros/landing_target/listen_lt: False

 * /mavros/landing_target/mav_frame: LOCAL_NED

 * /mavros/landing_target/target_size/x: 0.3

 * /mavros/landing_target/target_size/y: 0.3

 * /mavros/landing_target/tf/child_frame_id: camera_center

 * /mavros/landing_target/tf/frame_id: landing_target

 * /mavros/landing_target/tf/listen: False

 * /mavros/landing_target/tf/rate_limit: 10.0

 * /mavros/landing_target/tf/send: True

 * /mavros/local_position/frame_id: map

 * /mavros/local_position/tf/child_frame_id: base_link

 * /mavros/local_position/tf/frame_id: map

 * /mavros/local_position/tf/send: False

 * /mavros/local_position/tf/send_fcu: False

 * /mavros/mission/pull_after_gcs: True

 * /mavros/mission/use_mission_item_int: True

 * /mavros/mocap/use_pose: True

 * /mavros/mocap/use_tf: False

 * /mavros/odometry/fcu/odom_child_id_des: base_link

 * /mavros/odometry/fcu/odom_parent_id_des: map

 * /mavros/plugin_blacklist: ['safety_area', '...

 * /mavros/plugin_whitelist: []

 * /mavros/px4flow/frame_id: px4flow

 * /mavros/px4flow/ranger_fov: 0.118682

 * /mavros/px4flow/ranger_max_range: 5.0

 * /mavros/px4flow/ranger_min_range: 0.3

 * /mavros/safety_area/p1/x: 1.0

 * /mavros/safety_area/p1/y: 1.0

 * /mavros/safety_area/p1/z: 1.0

 * /mavros/safety_area/p2/x: -1.0

 * /mavros/safety_area/p2/y: -1.0

 * /mavros/safety_area/p2/z: -1.0

 * /mavros/setpoint_accel/send_force: False

 * /mavros/setpoint_attitude/reverse_thrust: False

 * /mavros/setpoint_attitude/tf/child_frame_id: target_attitude

 * /mavros/setpoint_attitude/tf/frame_id: map

 * /mavros/setpoint_attitude/tf/listen: False

 * /mavros/setpoint_attitude/tf/rate_limit: 50.0

 * /mavros/setpoint_attitude/use_quaternion: False

 * /mavros/setpoint_position/mav_frame: LOCAL_NED

 * /mavros/setpoint_position/tf/child_frame_id: target_position

 * /mavros/setpoint_position/tf/frame_id: map

 * /mavros/setpoint_position/tf/listen: False

 * /mavros/setpoint_position/tf/rate_limit: 50.0

 * /mavros/setpoint_raw/thrust_scaling: 1.0

 * /mavros/setpoint_velocity/mav_frame: LOCAL_NED

 * /mavros/startup_px4_usb_quirk: True

 * /mavros/sys/disable_diag: False

 * /mavros/sys/min_voltage: 10.0

 * /mavros/target_component_id: 1

 * /mavros/target_system_id: 1

 * /mavros/tdr_radio/low_rssi: 40

 * /mavros/time/time_ref_source: fcu

 * /mavros/time/timesync_avg_alpha: 0.6

 * /mavros/time/timesync_mode: MAVLINK

 * /mavros/vibration/frame_id: base_link

 * /mavros/vision_pose/tf/child_frame_id: vision_estimate

 * /mavros/vision_pose/tf/frame_id: odom

 * /mavros/vision_pose/tf/listen: False

 * /mavros/vision_pose/tf/rate_limit: 10.0

 * /mavros/vision_speed/listen_twist: True

 * /mavros/vision_speed/twist_cov: True

 * /mavros/wheel_odometry/child_frame_id: base_link

 * /mavros/wheel_odometry/count: 2

 * /mavros/wheel_odometry/frame_id: odom

 * /mavros/wheel_odometry/send_raw: True

 * /mavros/wheel_odometry/send_twist: False

 * /mavros/wheel_odometry/tf/child_frame_id: base_link

 * /mavros/wheel_odometry/tf/frame_id: odom

 * /mavros/wheel_odometry/tf/send: False

 * /mavros/wheel_odometry/use_rpm: False

 * /mavros/wheel_odometry/vel_error: 0.1

 * /mavros/wheel_odometry/wheel0/radius: 0.05

 * /mavros/wheel_odometry/wheel0/x: 0.0

 * /mavros/wheel_odometry/wheel0/y: -0.15

 * /mavros/wheel_odometry/wheel1/radius: 0.05

 * /mavros/wheel_odometry/wheel1/x: 0.0

 * /mavros/wheel_odometry/wheel1/y: 0.15

 * /rosdistro: noetic

 * /rosversion: 1.15.14

 * /trajectory_publisher/initpos_z: 2.0

 * /trajectory_publisher/reference_type: 2

 * /trajectory_publisher/shape_omega: 1.2

 * /trajectory_publisher/trajectory_type: 1

 * /use_sim_time: True

​

NODES

  /

    gazebo (gazebo_ros/gzserver)

    gazebo_gui (gazebo_ros/gzclient)

    geometric_controller (geometric_controller/geometric_controller_node)

    mavros (mavros/mavros_node)

    rqt_reconfigure (rqt_reconfigure/rqt_reconfigure)

    rviz (rviz/rviz)

    sitl (px4/px4)

    trajectory_publisher (trajectory_publisher/trajectory_publisher)

    vehicle_spawn_wahihi_VirtualBox_13686_3301694023482068349 (gazebo_ros/spawn_model)

​

ROS_MASTER_URI=http://localhost:11311/

​

process[geometric_controller-1]: started with pid [13701]

process[trajectory_publisher-2]: started with pid [13702]

process[rqt_reconfigure-3]: started with pid [13707]

process[mavros-4]: started with pid [13713]

[ INFO] [1654827947.487668631, 3669.816000000]: Reconfigure request : max_acc = 8.00 

[ INFO] [1654827947.519623798, 3669.848000000]: Waiting for home pose...

[ INFO] [1654827947.577274458]: FCU URL: udp://:14540@127.0.0.1:14557

[ INFO] [1654827947.584779837]: udp0: Bind address: 0.0.0.0:14540

[ INFO] [1654827947.584889429]: udp0: Remote address: 127.0.0.1:14557

[ INFO] [1654827947.585072111]: GCS bridge disabled

[ INFO] [1654827947.619020373]: Plugin 3dr_radio loaded

[ INFO] [1654827947.621232175]: Plugin 3dr_radio initialized

[ INFO] [1654827947.621348795]: Plugin actuator_control loaded

[ INFO] [1654827947.630985971]: Plugin actuator_control initialized

[ INFO] [1654827947.655488760]: Plugin adsb loaded

[ INFO] [1654827947.664213285, 3669.992000000]: Plugin adsb initialized

[ INFO] [1654827947.666418863, 3669.996000000]: Plugin altitude loaded

[ INFO] [1654827947.667070914, 3669.996000000]: Plugin altitude initialized

[ INFO] [1654827947.667811091, 3669.996000000]: Plugin cam_imu_sync loaded

[ INFO] [1654827947.670416898, 3670.000000000]: Plugin cam_imu_sync initialized

[ INFO] [1654827947.670577229, 3670.000000000]: Plugin camera loaded

[ INFO] [1654827947.672497793, 3670.000000000]: Plugin camera initialized

[ INFO] [1654827947.672675841, 3670.000000000]: Plugin command loaded

[ INFO] [1654827947.687634087, 3670.016000000]: Plugin command initialized

[ INFO] [1654827947.690947394, 3670.020000000]: Plugin companion_process_status loaded

[ INFO] [1654827947.698221928, 3670.024000000]: Plugin companion_process_status initialized

[ INFO] [1654827947.699115229, 3670.028000000]: Plugin debug_value loaded

[ INFO] [1654827947.704001821, 3670.032000000]: Plugin debug_value initialized

[ INFO] [1654827947.704153565, 3670.032000000]: Plugin distance_sensor blacklisted

[ INFO] [1654827947.705365146, 3670.032000000]: Plugin esc_status loaded

[ INFO] [1654827947.709574510, 3670.036000000]: Plugin esc_status initialized

[ INFO] [1654827947.709803391, 3670.036000000]: Plugin esc_telemetry loaded

[ INFO] [1654827947.713064209, 3670.040000000]: Plugin esc_telemetry initialized

[ INFO] [1654827947.713310276, 3670.040000000]: Plugin fake_gps loaded

[ INFO] [1654827947.755666990, 3670.084000000]: Plugin fake_gps initialized

[ INFO] [1654827947.755954474, 3670.084000000]: Plugin ftp loaded

[ INFO] [1654827947.776818581, 3670.104000000]: Plugin ftp initialized

[ INFO] [1654827947.777047000, 3670.104000000]: Plugin geofence loaded

[ INFO] [1654827947.793716917, 3670.120000000]: Plugin geofence initialized

[ INFO] [1654827947.793894116, 3670.120000000]: Plugin global_position loaded

INFO  [px4] PX4 daemon already running for instance 0 (Success)

failed to start local process: /home/wahihi/src/Firmware/build/px4_sitl_default/bin/px4 /home/wahihi/src/Firmware/build/px4_sitl_default/etc -s etc/init.d-posix/rcS __name:=sitl __log:=/home/wahihi/.ros/log/1271b0e8-e85c-11ec-9955-13fe95e71a1f/sitl-5.log

local launch of px4/px4 failed

[ INFO] [1654827947.849503859, 3670.176000000]: Plugin global_position initialized

[ INFO] [1654827947.849644173, 3670.176000000]: Plugin gps_input loaded

process[gazebo-6]: started with pid [13725]

================================================================================REQUIRED process [sitl-5] has died!

process has died [pid -1, exit code 255, cmd /home/wahihi/src/Firmware/build/px4_sitl_default/bin/px4 /home/wahihi/src/Firmware/build/px4_sitl_default/etc -s etc/init.d-posix/rcS __name:=sitl __log:=/home/wahihi/.ros/log/1271b0e8-e85c-11ec-9955-13fe95e71a1f/sitl-5.log].

log file: /home/wahihi/.ros/log/1271b0e8-e85c-11ec-9955-13fe95e71a1f/sitl-5*.log

Initiating shutdown!

================================================================================[ INFO] [1654827947.869619412, 3670.196000000]: Plugin gps_input initialized

[ INFO] [1654827947.871909011, 3670.200000000]: Plugin gps_rtk loaded

​

RLException: cannot add process [gazebo_gui-7] after process monitor has been shut down

The traceback for the exception was written to the log file

[ INFO] [1654827947.881374576, 3670.208000000]: Plugin gps_rtk initialized

[ INFO] [1654827947.881530134, 3670.208000000]: Plugin gps_status loaded

[ INFO] [1654827947.887012403, 3670.216000000]: Plugin gps_status initialized

[ INFO] [1654827947.887195530, 3670.216000000]: Plugin hil loaded

[ INFO] [1654827947.929520816, 3670.256000000]: Plugin hil initialized

[ INFO] [1654827947.929697668, 3670.256000000]: Plugin home_position loaded

[ INFO] [1654827947.939182704, 3670.268000000]: Plugin home_position initialized

[ INFO] [1654827947.939402906, 3670.268000000]: Plugin imu loaded

[ INFO] [1654827947.969226022, 3670.296000000]: Plugin imu initialized

[ INFO] [1654827947.969394926, 3670.296000000]: Plugin landing_target loaded

[gazebo-6] killing on exit

[sitl-5] killing on exit

[mavros-4] killing on exit

[rqt_reconfigure-3] killing on exit

[trajectory_publisher-2] killing on exit

[geometric_controller-1] killing on exit

Traceback (most recent call last):

  File "/opt/ros/noetic/lib/rqt_reconfigure/rqt_reconfigure", line 5, in <module>

    from rqt_reconfigure.__main__ import main

  File "/opt/ros/noetic/lib/python3/dist-packages/rqt_reconfigure/__main__.py", line 35, in <module>

    from rqt_gui.main import Main

  File "/opt/ros/noetic/lib/python3/dist-packages/rqt_gui/main.py", line 41, in <module>

    import rospy

  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/__init__.py", line 47, in <module>

    from std_msgs.msg import Header

  File "/opt/ros/noetic/lib/python3/dist-packages/std_msgs/msg/__init__.py", line 1, in <module>

    from ._Bool import *

  File "/opt/ros/noetic/lib/python3/dist-packages/std_msgs/msg/_Bool.py", line 6, in <module>

    import genpy

  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/__init__.py", line 34, in <module>

    from . message import Message, SerializationError, DeserializationError, MessageException, struct_I

  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/message.py", line 64, in <module>

    import numpy as np

Traceback (most recent call last):

  File "/opt/ros/noetic/bin/catkin_find", line 5, in <module>

    import argparse

  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 187, in <module>

    from .testing import Tester

  File "/usr/lib/python3.8/argparse.py", line 88, in <module>

    import re as _re

  File "/usr/lib/python3/dist-packages/numpy/testing/__init__.py", line 10, in <module>

  File "/usr/lib/python3.8/re.py", line 125, in <module>

    import sre_compile

  File "/usr/lib/python3.8/sre_compile.py", line 14, in <module>

    import sre_parse

  File "/usr/lib/python3.8/sre_parse.py", line 15, in <module>

    from unittest import TestCase

  File "/usr/lib/python3.8/unittest/__init__.py", line 60, in <module>

    from sre_constants import *

    from .async_case import IsolatedAsyncioTestCase

  File "/usr/lib/python3.8/unittest/async_case.py", line 1, in <module>

  File "/usr/lib/python3.8/sre_constants.py", line 75, in <module>

    import asyncio

  File "<frozen importlib._bootstrap>", line 991, in _find_and_load

  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked

  File "<frozen importlib._bootstrap>", line 562, in module_from_spec

  File "<frozen importlib._bootstrap>", line 541, in _init_module_attrs

  File "<frozen importlib._bootstrap>", line 379, in cached

KeyboardInterrupt

    OPCODES = _makecodes("""

  File "/usr/lib/python3.8/sre_constants.py", line 69, in _makecodes

    items = [_NamedIntConstant(i, name) for i, name in enumerate(names)]

  File "/usr/lib/python3.8/sre_constants.py", line 69, in <listcomp>

    items = [_NamedIntConstant(i, name) for i, name in enumerate(names)]

  File "/usr/lib/python3.8/sre_constants.py", line 58, in __new__

    self = super(_NamedIntConstant, cls).__new__(cls, value)

KeyboardInterrupt

wahihi@wahihi-VirtualBox:~/catkin_ws$
```

**Comment by Jaeyoung-Lim** [comment]
```
process has died [pid -1, exit code 255, cmd /home/wahihi/src/Firmware/build/px4_sitl_default/bin/px4 /home/wahihi/src/Firmware/build/px4_sitl_default/etc -s etc/init.d-posix/rcS __name:=sitl __log:=/home/wahihi/.ros/log/1271b0e8-e85c-11ec-9955-13fe95e71a1f/sitl-5.log].

log file: /home/wahihi/.ros/log/1271b0e8-e85c-11ec-9955-13fe95e71a1f/sitl-5*.log

Initiating shutdown!
```
Are you sure you have built PX4 SITL and run the sitl gazebo environment without using mavros?

**Comment by wahihijames** [comment]
> ```
> process has died [pid -1, exit code 255, cmd /home/wahihi/src/Firmware/build/px4_sitl_default/bin/px4 /home/wahihi/src/Firmware/build/px4_sitl_default/etc -s etc/init.d-posix/rcS __name:=sitl __log:=/home/wahihi/.ros/log/1271b0e8-e85c-11ec-9955-13fe95e71a1f/sitl-5.log].
> 
> log file: /home/wahihi/.ros/log/1271b0e8-e85c-11ec-9955-13fe95e71a1f/sitl-5*.log
> 
> Initiating shutdown!
> ```
> 
> Are you sure you have built PX4 SITL and run the sitl gazebo environment without using mavros?

Thank you Reply.
I solved my issue.
Although catkin_ws was already installed, it was installed again, and the path was tangled.

I have another question.
$roslaunch geometric_controller sitl_trajectory_track_circle.launch
When I run , all Gazebo etc. appear, but the drone is only arming and not taking off. (See attached video) What did I do wrong? The log file generated by QGroundControl is attached. please check.

[첨부파일 password: 1234](http://naver.me/5WGMhKHo)
#

catkin_ws가 이미 설치가 되어 있는데, 또 설치를 하게 되어서, path가 엉클어져서 생긴 문제 였습니다.
또 하나 질문이 있는데요. 
roslaunch geometric_controller sitl_trajectory_track_circle.launch
을 실행시키니, Gazebo 등은 전부 나오는데, 드론이 Arming 만 하고 있고, 이륙을 안하네요.  (첨부한 동영상 참조) 제가 무엇을 잘못해서 생긴것일까요?  QGroundControl에서 생성한 로그파일을 첨부 합니다. 확인 부탁드립니다.

**Comment by Jaeyoung-Lim** [comment]
@wahihijames Was the problem solved?

On the video it looks like the video has already crashed to the ground

**Comment by wahihi** [comment]
> On the video it looks like the video has already crashed to the ground

Thank you. your Reply. 
I solved this problem. Just Rebooting my Ubuntu..  It's likes crazy.   Ubuntu looks like Windows OS..  :)

**Comment by Jaeyoung-Lim** [comment]
@wahihi Great to hear that it was fixed! Closing!
